import elvisImage from "./images/elvis.png";

function About() {
  return (
    <div className="row mt-5">
      <div className="col-md-6 col-sm-12 order-md-last">
        <h1 id="about">About</h1>
        <p className="lead">
          MeVerse is a collection of 10,000 unique works of art carefully
          generated by the world’s greatest artists, you.
        </p>
        <p className="lead">
          Our <strong className="text-blue">VISION</strong>: to give you, for
          the first time, the opportunity to choose items for your character and
          directly influence the rarity of NFTs. But there is more! You will
          also be able to choose the personality traits based on which you will
          be clustered into different groups.
        </p>
        <p className="lead">
          And then collaborate with others.
          <br />
          And then play games.
          <br />
          And then "work".
          <br />
          And then ... Ok we can't get into too much details now
          <br />
        </p>
        <p className="lead">
          Our <strong className="text-blue">MISSION</strong>: Bring new,
          original, revolutionary initiatives into the NFT Metaverse built
          around you.
        </p>
      </div>
      <div className="col-md-6 col-sm-12 d-flex flex-column">
        <img
          src={elvisImage}
          className="img-fluid mx-auto my-auto"
          alt="Oops.."
        />
      </div>
    </div>
  );
}

export default About;
