import Footer from "./Footer";
import hero from "./images/hero.svg";
import ruby from "./images/ruby.png";
import elvis from "./images/elvis.png";
import ethereum from "./images/ethereum.png";
import "./App.scss";

function App() {
  return (
    <div className="container-fluid m-0 App">
      <div className="container pt-5">
        <div className="col vh-100 d-flex flex-column App-hero">
          <div className="col pt-3">
            <h1 className="App-title text-center">Welcome To MeVerse</h1>
            <blockquote className="blockquote text-center mt-4">
              <p className="fs-2">
                In a MetaVerse where you can be anything,
                <br /> be <span className="App-blue-text"> yourself</span>!
              </p>
              <footer className="blockquote-footer fs-5">
                Some metaphysician 420 B.C.
              </footer>
            </blockquote>
          </div>
          <div className="col">
            <img src={hero} className="img-fluid App-cover" alt="Ooops.." />
          </div>
          <div className="col d-flex flex-column">
            <div className="row mx-auto">
              <a
                href="https://discord.gg/gT8gtSPkTc"
                target="_blank"
                rel="noreferrer"
                className="btn btn-success px-4 App-join-button"
              >
                <i className="bi bi-discord" />
                &nbsp; Join us on Discord
              </a>
            </div>
          </div>
        </div>
        <div className="row">
          <div className="col d-flex flex-column">
            <img src={elvis} className="mx-auto" alt="Oops.." />
          </div>
          <div className="col App-about">
            <h1 id="about">About Collection</h1>
            <p>
              MeVerse is a collection of 10,000 unique works of art carefully
              generated by the world’s greatest artists, you.
            </p>
            <p>
              Our <strong className="App-blue-text">VISION</strong>: to give
              you, for the first time, the opportunity to choose items for your
              character and directly influence the rarity of NFTs. But there is
              more! You will also be able to choose the personality traits based
              on which you will be clustered into different groups.
            </p>
            <p>
              And then collaborate with others.
              <br />
              And then play games.
              <br />
              And then "work".
              <br />
              And then ... Ok we can't get into too much details now
              <br />
            </p>
            <p>
              Our <strong className="App-blue-text">MISSION</strong>: Bring new,
              original, revolutionary initiatives into the NFT Metaverse built
              around you.
            </p>
          </div>
        </div>
        <div className="row mt-5">
          <div className="col App-about">
            <h1 id="about">Rarity</h1>
            <p>
              There is no predetermined rarity system for our item collection.
              It depends only on your choice. Since you can select items for
              your character, whatever gets chosen the most will have the least
              value. And opposite. You can be creative and make your Meridian
              stand out! And, in addition, we are introducing a completely new
              perspective into the Rarity System. Through your
              real/desired/chosen personality traits. Just wait.
            </p>
          </div>
          <div className="col text-center">
            <img src={ruby} className="mt-5" alt="Oops.." />
          </div>
        </div>

        <div className="col mt-5">
          <div className="row text-center">
            <h1 id="minting">Minting</h1>
          </div>
          <div className="row mt-3">
            <div className="col-lg-4 text-end my-auto">
              <img src={ethereum} className="img-fluid" alt="Ooops.." />
            </div>
            <div className="col-lg-8">
              <div className="row mb-3">
                <div className="col-lg-3 text-end App-timeline">
                  <span className="display-6 App-hero">10%</span>
                </div>
                <div className="col d-flex flex-column">
                  <p className="my-auto">
                    Flying Meridians. We will airdrop 10 NFT Meridians to
                    random, lucky minters.
                  </p>
                </div>
              </div>
              <div className="row mb-3">
                <div className="col-lg-3 text-end App-timeline">
                  <span className="display-6 App-hero">25%</span>
                </div>
                <div className="col d-flex flex-column">
                  <p className="my-auto">Real life drop for 20 Meridians.</p>
                </div>
              </div>
              <div className="row mb-3">
                <div className="col-lg-3 text-end App-timeline">
                  <span className="display-6 App-hero">50%</span>
                </div>
                <div className="col d-flex flex-column">
                  <p className="my-auto">
                    Giving back to the community. 5000 $ for 10 holders.
                  </p>
                </div>
              </div>
              <div className="row mb-3">
                <div className="col-lg-3 text-end App-timeline">
                  <span className="display-6 App-hero">75%</span>
                </div>
                <div className="col d-flex flex-column">
                  <p className="my-auto">
                    For the greater cause! We will donate 100,000$ to the
                    organization by YOUR choice.
                  </p>
                </div>
              </div>
              <div className="row mb-3">
                <div className="col-lg-3 text-end App-timeline">
                  <span className="display-6 App-hero">100%</span>
                </div>
                <div className="col d-flex flex-column">
                  <p className="my-auto">
                    Gigameridians. There will be one ultra-rare Meridian for
                    each group. Pray that you will be one of the lucky winners,
                    because if you are, you won’t be the same person ever again.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="col mt-5">
          <div className="row text-center">
            <h1 id="team">Team</h1>
          </div>
          <div className="row text-center mt-3">
            <div className="col">
              <img src={elvis} alt="Oops.." width="200" height="200" />
              <h2 className="mt-3 App-hero">DJ Ape</h2>
              <p>Sentinel with get ritches, fuck bitches mentality.</p>
            </div>
            <div className="col">
              <img src={elvis} alt="Oops.." width="200" height="200" />
              <h2 className="mt-3 App-hero">Mimi</h2>
              <p>
                Adventurer. Experience over things. Journey over destination.
              </p>
            </div>
            <div className="col">
              <img src={elvis} alt="Oops.." width="200" height="200" />
              <h2 className="mt-3 App-hero">Daka</h2>
              <p>Chad. It was an easy decision who Chad is in this group!</p>
            </div>
            <div className="col">
              <img src={elvis} alt="Oops.." width="200" height="200" />
              <h2 className="mt-3 App-hero">Anya</h2>
              <p>Thinker. Building Web 3.0, block by block.</p>
            </div>
            <div className="col">
              <img src={elvis} alt="Oops.." width="200" height="200" />
              <h2 className="mt-3 App-hero">Greesin</h2>
              <p>
                Leader. Marching with my team on the frontiers of the Metaverse,
                driven by innovation.
              </p>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}

export default App;
